// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnHfFB7BVmByoQMgHAdAWqdyXhedeU0W4',
    appId: '1:727528034335:web:a480897a39fb08c0e5852a',
    messagingSenderId: '727528034335',
    projectId: 'anti-rigging',
    authDomain: 'anti-rigging.firebaseapp.com',
    storageBucket: 'anti-rigging.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPQQU54qIK75f6S4H83KkqHEBD34rdiIw',
    appId: '1:727528034335:android:e8431968da2991b9e5852a',
    messagingSenderId: '727528034335',
    projectId: 'anti-rigging',
    storageBucket: 'anti-rigging.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzufBBf3BtNmi3jtwnmyaUIvy5cXLc1V8',
    appId: '1:727528034335:ios:ee13a4f51ac622b0e5852a',
    messagingSenderId: '727528034335',
    projectId: 'anti-rigging',
    storageBucket: 'anti-rigging.appspot.com',
    iosBundleId: 'com.example.antiRigging',
  );
}
